### ISSUE TITLE
Circular progress not visible on react-native-web

### ISSUE THREAD

**Issue by crstnmac** [adaptui/react-native-tailwind#75]
https://github.com/react-native-svg/react-native-svg/pull/1886

**Comment by crstnmac** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/3321

**Comment by Karthik-B-06** [comment]
I think it's fixed in the [latest version](https://github.com/software-mansion/react-native-svg/releases/tag/v.13.5.0). Have to update and check. 

![Screenshot 2022-11-05 at 3 11 54 PM](https://user-images.githubusercontent.com/35562287/200113594-dd1698de-63de-48fe-b5c9-358762a2f12f.png)

**Comment by Karthik-B-06** [comment]
This has been fixed after updating the reanimated package versions. 

![Screenshot 2022-12-01 at 6 56 32 PM](https://user-images.githubusercontent.com/35562287/205064512-99e984d3-8a82-4a49-abb1-c3f117248b73.png)
